### ISSUE TITLE
hibernate.reveng.xml -- no closing tag

### ISSUE THREAD

**Issue by gesker** [institut-de-genomique/hibernatetools-gradle-plugin#1]
</hibernate-reverse-engineering> does not seem to be added to the end of the hibernate.reveng.xml file on first run of gradle hibernate-config

Using  id "org.hibernate.gradle.tools" version "1.2.3" on gradle 2.6 on jdk 1.8

**Comment by yrpatil** [comment]
I am also facing same issue.

**Comment by bioinfornatics** [comment]
the latest version 1.2.4 should fix this
