### ISSUE TITLE
Port automatically added to JDBC url

### ISSUE THREAD

**Issue by gesker** [institut-de-genomique/hibernatetools-gradle-plugin#3]
This breaks the url for PostgreSQL

jdbc:postgresql://localhost:5432/dbName becomes
jdbc:postgresql://localhost:5432/aui:3306

if set port = 5432
jdbc:postgresql://localhost:5432/dbName becomes
jdbc:postgresql://localhost:5432/aui:5432

**Comment by bioinfornatics** [comment]
hi sorry for the time, I had lot of others projects in top priority.

So I think you have done a wrong database configuration for your purpose can you try:

```
database {
    url     = "jdbc:postgresql://localhost"
    catalog = [ "dbName": new Schema() ]
    port    =  5432
}
```

I think this will solve your issue. Tell me if that works .
If not you are welcome to re-open it this issue .

Thanks

**Comment by AdelaKaraman** [comment]
I have similar problem with mysql. I tried solution you suggested but still getting error:

`java.sql.SQLException: The connection property 'useSSL' only accepts values of the form: 'true', 'false', 'yes' or 'no'. The value 'true:3306' is not in this set.
:hbm2java FAILED`
