### ISSUE TITLE
Feature request: Use existing hibernate.cfg.xml and hibernate.reveng.xml as an option

### ISSUE THREAD

**Issue by gesker** [institut-de-genomique/hibernatetools-gradle-plugin#5]
After "gradle hibernate-config" I'd like to put these files else ware in my gradle build (no need to re-generate). 

Could two vailables be added to the main class to pull these from a standard location like src/resources ?

**Comment by bioinfornatics** [comment]
Thanks gesker,

I agree with you I will think a way to copy config files from build directory to the resources directory.

I will come back with a proposal.

You are welcome
