### ISSUE TITLE
Please help me with hbm2java.

### ISSUE THREAD

**Issue by yrpatil** [institut-de-genomique/hibernatetools-gradle-plugin#7]
I am newbie to gradle. I am trying to generate java model (POJO) classes from table schema. 
I am not sure what is going wrong. It is not giving any error. Please find attached build.gradle file. And if i see content of hibernate.reveng.xml file is incorrect XML (find attached image). 
Please help me generate POJO's.

![image](https://cloud.githubusercontent.com/assets/14276935/10097308/ceb2b750-6395-11e5-94ed-49383cca0ef3.png)

![image](https://cloud.githubusercontent.com/assets/14276935/10097260/866ed49c-6395-11e5-8fb2-0ff31b64c3e8.png)

**Comment by bioinfornatics** [comment]
sorry was an internal bug latest release 1.2.4 should fix it
